project_name: enum
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
  - maintainer: Dr Ogg <ogg@sr375.com
    description: enum
    homepage: https://github.com/DoctorOgg/enum/
    license: MIT
    formats:
      - deb
      - rpm

archives:
  - id: tar
    format: tar.gz
    files:
      - README.md
